# For more information, see: https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-5.16

# Local packages, usually specified by relative directory name
packages:
- '.'
- location:
        git: https://github.com/martinra/natural-test.git
        commit: c950ee97dd287e0fbfe79b8e0394c407e2928ee8
- location:
        git: https://github.com/martinra/vector-test.git
        commit: dca07e04faa570848bdf2b5207d5ed8996ef1264
- location:
        git: https://github.com/martinra/algebraic-structures.git
        commit: 9be501381c6eb136c365957ed1478c3c9ce8777c
- location:
        git: https://github.com/martinra/hflint.git
        commit: a6906394df998561d4a2be672acf685c8746a4d8

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps: [ permutation-0.5.0.5
            , random-extras-0.19
            , tuple-0.3.0.2
            , OneTuple-0.2.1]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true

# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: >= 1.0.0

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64

# Extra directories used by stack for building
